version: "3.8"
services:
  graph_store:
    build: graph_store/
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
    command: python graph_store.py populate
    depends_on:
      - enricher
  enricher:
    build: enricher/
    ports:
      - 80:80
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
  tests:
    build: .
    command: python -m pytest ./graph_store/test/ ./enricher/test/
